name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["FEATURE"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Requirements
      options:
        - label: I have written the whole issue myself and I am not an AI Agent. Check [CONTRIBUTING.MD](https://github.com/Elnix90/Dragon-Launcher?tab=contributing-ov-file) for more info
          required: true
        - label: I checked for duplicate issues in both opened and closed and searched in the whole app / asked if the feature isn't already implemented
          required: true
        - label: I updated the app to the latest version and and searched in the whole app / asked if the feature isn't already implemented
          required: true
        - label: I verified that the issue
          required: false
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of the feature request.
      placeholder: What feature would you like to see?
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: Is there a problem this feature would solve? If so, describe it.
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: How would you like this feature to work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Are there any alternative solutions you've considered?
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
